export type TemplateTheme = {
  name: string;
  mode: "dark" | "light";
  bg: string;            // page background (colour or gradient)
  bgSolid: string;       // flat colour used for contrast checks
  card: string;          // card surface, SOLID colour (no transparency under text)
  text: string;          // main text
  textMuted: string;     // secondary text (still >= 4.5:1)
  accent: string;        // headings highlight, name, borders
  accentText: string;    // text placed ON an accent fill (buttons)
  border: string;
  radius: string;        // e.g. "28px", "2px", "0"
  shadow: string;
  texture: "none" | "paper" | "grain" | "scanlines" | "grid" | "halftone";
  fontDisplay: string;   // CSS var name, e.g. "var(--font-cinzel)"
  fontBody: string;
  fontMono?: string;
  nameScale: number;     // multiplier for the name size
};

export const THEMES: Record<number, TemplateTheme> = {
  1: {
    name: "Ceremony",
    mode: "dark",
    bg: "#0b0710",
    bgSolid: "#0b0710",
    card: "#fbf3df",
    text: "#2a1a05",
    textMuted: "#5a4520",
    accent: "#8a6508",
    accentText: "#ffffff",
    border: "2px solid var(--accent)",
    radius: "2px",
    shadow: "0 10px 30px rgba(0,0,0,0.5)",
    texture: "paper",
    fontDisplay: "var(--font-cinzel)",
    fontBody: "var(--font-cormorant)",
    nameScale: 1.0,
  },
  2: {
    name: "Cyber",
    mode: "dark",
    bg: "#02060f",
    bgSolid: "#02060f",
    card: "#07131f",
    text: "#e6fbff",
    textMuted: "#9fc9d6",
    accent: "#00e5ff",
    accentText: "#001018",
    border: "1px solid var(--accent)",
    radius: "0px",
    shadow: "0 0 20px rgba(0, 229, 255, 0.2)",
    texture: "scanlines",
    fontDisplay: "var(--font-orbitron)",
    fontBody: "var(--font-rajdhani)",
    fontMono: "var(--font-share-tech-mono)",
    nameScale: 1.2,
  },
  3: {
    name: "PlayerOne",
    mode: "dark",
    bg: "#0d0221",
    bgSolid: "#0d0221",
    card: "#1a0b3d",
    text: "#ffffff",
    textMuted: "#cbb8ff",
    accent: "#ffd60a",
    accentText: "#1a0b3d",
    border: "4px solid var(--accent)",
    radius: "8px",
    shadow: "4px 4px 0px var(--accent)",
    texture: "grid",
    fontDisplay: "var(--font-press-start)",
    fontBody: "var(--font-exo2)",
    nameScale: 0.8,
  },
  4: {
    name: "Cinematic",
    mode: "dark",
    bg: "#000000",
    bgSolid: "#000000",
    card: "#14110d",
    text: "#f5ecd7",
    textMuted: "#c9bd9f",
    accent: "#e0b252",
    accentText: "#14110d",
    border: "1px solid var(--accent)",
    radius: "0px",
    shadow: "0 20px 40px rgba(0,0,0,0.8)",
    texture: "grain",
    fontDisplay: "var(--font-bebas-neue)",
    fontBody: "var(--font-playfair)",
    nameScale: 1.5,
  },
  5: {
    name: "Space",
    mode: "dark",
    bg: "#03030f",
    bgSolid: "#03030f",
    card: "#0c1230",
    text: "#eef2ff",
    textMuted: "#b4c0f0",
    accent: "#7dd3fc",
    accentText: "#03111f",
    border: "1px solid rgba(125, 211, 252, 0.3)",
    radius: "16px",
    shadow: "0 0 30px rgba(125, 211, 252, 0.1)",
    texture: "none",
    fontDisplay: "var(--font-space-grotesk)",
    fontBody: "var(--font-exo2)",
    nameScale: 1.1,
  },
  6: {
    name: "Terminal",
    mode: "dark",
    bg: "#000000",
    bgSolid: "#000000",
    card: "#04120a",
    text: "#b6ffcb",
    textMuted: "#7fd9a0",
    accent: "#39ff88",
    accentText: "#001a0a",
    border: "2px solid var(--accent)",
    radius: "0px",
    shadow: "none",
    texture: "scanlines",
    fontDisplay: "var(--font-vt323)",
    fontBody: "var(--font-jetbrains)",
    fontMono: "var(--font-jetbrains)",
    nameScale: 1.3,
  },
  7: {
    name: "Elegant",
    mode: "light",
    bg: "#faf8f4",
    bgSolid: "#faf8f4",
    card: "#ffffff",
    text: "#1a1a1a",
    textMuted: "#55504a",
    accent: "#7a5c2a",
    accentText: "#ffffff",
    border: "1px solid #e5e0d8",
    radius: "4px",
    shadow: "0 10px 40px rgba(0,0,0,0.05)",
    texture: "paper",
    fontDisplay: "var(--font-cormorant)",
    fontBody: "var(--font-inter)",
    nameScale: 1.2,
  },
  8: {
    name: "Arcade",
    mode: "dark",
    bg: "#08001a",
    bgSolid: "#08001a",
    card: "#16003a",
    text: "#ffffff",
    textMuted: "#d6c8ff",
    accent: "#ff5cad",
    accentText: "#16003a",
    border: "2px solid var(--accent)",
    radius: "0px",
    shadow: "0 0 15px var(--accent)",
    texture: "grid",
    fontDisplay: "var(--font-press-start)",
    fontBody: "var(--font-vt323)",
    nameScale: 0.8,
  },
  9: {
    name: "Memory",
    mode: "light",
    bg: "#e9dfcf",
    bgSolid: "#e9dfcf",
    card: "#fffaf0",
    text: "#2b2118",
    textMuted: "#5b4a3a",
    accent: "#a3441f",
    accentText: "#ffffff",
    border: "8px solid #ffffff",
    radius: "2px",
    shadow: "0 4px 15px rgba(0,0,0,0.1)",
    texture: "paper",
    fontDisplay: "var(--font-caveat)",
    fontBody: "var(--font-special-elite)",
    nameScale: 1.4,
  },
  10: {
    name: "News",
    mode: "light",
    bg: "#d8d2c4",
    bgSolid: "#d8d2c4",
    card: "#f4efe3",
    text: "#111111",
    textMuted: "#444444",
    accent: "#a8001c",
    accentText: "#ffffff",
    border: "1px solid #333333",
    radius: "0px",
    shadow: "0 2px 10px rgba(0,0,0,0.1)",
    texture: "halftone",
    fontDisplay: "var(--font-playfair)",
    fontBody: "var(--font-libre-baskerville)",
    nameScale: 1.1,
  },
  11: {
    name: "Social",
    mode: "dark",
    bg: "#0f0f14",
    bgSolid: "#0f0f14",
    card: "#1b1b24",
    text: "#ffffff",
    textMuted: "#c4c4d4",
    accent: "#ff6aa2",
    accentText: "#1b1b24",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    radius: "24px",
    shadow: "0 10px 30px rgba(0,0,0,0.2)",
    texture: "none",
    fontDisplay: "var(--font-plus-jakarta)",
    fontBody: "var(--font-inter)",
    nameScale: 1.0,
  },
  12: {
    name: "AI",
    mode: "dark",
    bg: "#050a14",
    bgSolid: "#050a14",
    card: "#0b1626",
    text: "#e8f1ff",
    textMuted: "#9db6d6",
    accent: "#4dabff",
    accentText: "#04101f",
    border: "1px solid var(--accent)",
    radius: "12px",
    shadow: "0 0 20px rgba(77, 171, 255, 0.15)",
    texture: "grain",
    fontDisplay: "var(--font-sora)",
    fontBody: "var(--font-ibm-plex-mono)",
    fontMono: "var(--font-ibm-plex-mono)",
    nameScale: 1.1,
  },
  13: {
    name: "Journey",
    mode: "light",
    bg: "#cfe3f5",
    bgSolid: "#cfe3f5",
    card: "#f7fbff",
    text: "#1d2f4a",
    textMuted: "#3d5675",
    accent: "#2f5f99",
    accentText: "#ffffff",
    border: "none",
    radius: "16px",
    shadow: "0 15px 35px rgba(29, 47, 74, 0.1)",
    texture: "none",
    fontDisplay: "var(--font-lora)",
    fontBody: "var(--font-cormorant)",
    nameScale: 1.2,
  },
  14: {
    name: "Celebration",
    mode: "light",
    bg: "linear-gradient(135deg, #ff3d81 0%, #ff9e00 100%)",
    bgSolid: "#ff6b40",
    card: "#fff7e6",
    text: "#2b0a3d",
    textMuted: "#5b3a70",
    accent: "#c2185b",
    accentText: "#ffffff",
    border: "4px solid var(--accent)",
    radius: "20px",
    shadow: "0 10px 25px rgba(194, 24, 91, 0.2)",
    texture: "halftone",
    fontDisplay: "var(--font-bungee)",
    fontBody: "var(--font-poppins)",
    nameScale: 1.0,
  },
  15: {
    name: "Spotlight",
    mode: "dark",
    bg: "#050505",
    bgSolid: "#050505",
    card: "#1a0a0a",
    text: "#fff3e0",
    textMuted: "#e0c9a8",
    accent: "#ffcf5c",
    accentText: "#1a0a0a",
    border: "1px solid rgba(255, 207, 92, 0.3)",
    radius: "8px",
    shadow: "0 20px 50px rgba(0,0,0,0.8)",
    texture: "grain",
    fontDisplay: "var(--font-cinzel)",
    fontBody: "var(--font-playfair)",
    nameScale: 1.1,
  },
  16: {
    name: "Magazine",
    mode: "light",
    bg: "#f2f2f2",
    bgSolid: "#f2f2f2",
    card: "#ffffff",
    text: "#0a0a0a",
    textMuted: "#4a4a4a",
    accent: "#c40500",
    accentText: "#ffffff",
    border: "none",
    radius: "0px",
    shadow: "0 10px 30px rgba(0,0,0,0.1)",
    texture: "none",
    fontDisplay: "var(--font-bodoni)",
    fontBody: "var(--font-archivo)",
    nameScale: 1.3,
  },
  17: {
    name: "Mystery",
    mode: "dark",
    bg: "#0a0a0c",
    bgSolid: "#0a0a0c",
    card: "#15151a",
    text: "#ececec",
    textMuted: "#b5b5bd",
    accent: "#ff5a4f",
    accentText: "#15151a",
    border: "1px solid #333",
    radius: "4px",
    shadow: "0 5px 20px rgba(0,0,0,0.5)",
    texture: "grain",
    fontDisplay: "var(--font-special-elite)",
    fontBody: "var(--font-courier-prime)",
    fontMono: "var(--font-courier-prime)",
    nameScale: 1.1,
  },
  18: {
    name: "Passport",
    mode: "dark",
    bg: "#0d2b45",
    bgSolid: "#0d2b45",
    card: "#f3ead3",
    text: "#1b2a3a",
    textMuted: "#45566a",
    accent: "#0d2b45",
    accentText: "#ffffff",
    border: "2px solid #0d2b45",
    radius: "8px",
    shadow: "0 5px 15px rgba(0,0,0,0.3)",
    texture: "paper",
    fontDisplay: "var(--font-cinzel)",
    fontBody: "var(--font-courier-prime)",
    fontMono: "var(--font-courier-prime)",
    nameScale: 1.0,
  },
  19: {
    name: "Energy",
    mode: "dark",
    bg: "#ffe500",
    bgSolid: "#ffe500",
    card: "#000000",
    text: "#ffffff",
    textMuted: "#e6e6e6",
    accent: "#ffe500",
    accentText: "#000000",
    border: "3px solid var(--accent)",
    radius: "0px",
    shadow: "8px 8px 0px var(--accent)",
    texture: "halftone",
    fontDisplay: "var(--font-anton)",
    fontBody: "var(--font-space-grotesk)",
    nameScale: 1.2,
  },
  20: {
    name: "Portal",
    mode: "dark",
    bg: "#05010f",
    bgSolid: "#05010f",
    card: "#0f0620",
    text: "#f3eaff",
    textMuted: "#c9b8ea",
    accent: "#b388ff",
    accentText: "#12062a",
    border: "1px solid rgba(179, 136, 255, 0.4)",
    radius: "30px",
    shadow: "0 0 40px rgba(179, 136, 255, 0.2)",
    texture: "none",
    fontDisplay: "var(--font-orbitron)",
    fontBody: "var(--font-exo2)",
    nameScale: 1.1,
  }
};
